### ISSUE TITLE
unexpect group drop issue on linux bridge interface with multicast snooping

### ISSUE THREAD

**Issue by realdream** [troglobit/mrouted#42]
### Release info
version : 4.1
mrouted install method :  install from apt / build from source at git tag `4.1`
host system: ubuntu server 20.04/ debain 10.7
### Topology
![topology drawio](https://user-images.githubusercontent.com/7447946/102841030-17ed7b00-443f-11eb-8e82-037f9baf3b91.png)
### mrouted config
```
no phyint
phyint br0 enable
phyint enp1s0 enable
```
### Issue Description
* step1: setup system shown in topology figure
* step2: start 2 iperf receiver and 1 sender as shown in topology figure, both 2 receiver can get mc traffic on 239.255.1.1
* step3: use ctrl-c to stop the receiver 2 , ` receiver 1 will stop getting mc traffic on 239.255.1.1 after 3 seconds`

if we turnoff mulitcast_snooping on br0 by 
```
echo 0 > /sys/devices/virtual/net/br0/bridge/multicast_snooping
```
this issue will not reappear
#### mulitcast_snooping on
*igmp traffic on host1 br0 
```
03:56:22.466983 IP (tos 0xc0, ttl 1, id 0, offset 0, flags [DF], proto IGMP (2), length 40, options (RA))
    10.88.84.102 > 224.0.0.22: igmp v3 report, 1 group record(s) [gaddr 239.255.1.1 to_ex { }]
03:56:23.022989 IP (tos 0xc0, ttl 1, id 0, offset 0, flags [DF], proto IGMP (2), length 40, options (RA))
    10.88.84.102 > 224.0.0.22: igmp v3 report, 1 group record(s) [gaddr 239.255.1.1 to_ex { }]
03:56:25.434460 IP (tos 0xc0, ttl 1, id 0, offset 0, flags [DF], proto IGMP (2), length 40, options (RA))
    10.88.84.103 > 224.0.0.22: igmp v3 report, 1 group record(s) [gaddr 239.255.1.1 to_ex { }]
03:56:25.642460 IP (tos 0xc0, ttl 1, id 0, offset 0, flags [DF], proto IGMP (2), length 40, options (RA))
    10.88.84.103 > 224.0.0.22: igmp v3 report, 1 group record(s) [gaddr 239.255.1.1 to_ex { }]

03:56:28.466437 IP (tos 0xc0, ttl 1, id 0, offset 0, flags [DF], proto IGMP (2), length 40, options (RA))
    10.88.84.103 > 224.0.0.22: igmp v3 report, 1 group record(s) [gaddr 239.255.1.1 to_in { }]

03:56:28.466661 IP (tos 0xc0, ttl 1, id 38833, offset 0, flags [none], proto IGMP (2), length 36, options (RA))
    10.88.84.1 > 239.255.1.1: igmp query v3 [max resp time 1.0s]
03:56:28.466717 IP (tos 0xc0, ttl 1, id 38834, offset 0, flags [none], proto IGMP (2), length 36, options (RA))
    10.88.84.1 > 239.255.1.1: igmp query v3 [max resp time 1.0s]

03:56:28.866371 IP (tos 0xc0, ttl 1, id 0, offset 0, flags [DF], proto IGMP (2), length 40, options (RA))
    10.88.84.103 > 224.0.0.22: igmp v3 report, 1 group record(s) [gaddr 239.255.1.1 to_in { }]
03:56:28.866581 IP (tos 0xc0, ttl 1, id 38913, offset 0, flags [none], proto IGMP (2), length 36, options (RA))
    10.88.84.1 > 239.255.1.1: igmp query v3 [max resp time 1.0s]
```
*igmp traffic on host3 eth0
```
13:34:15.766655 IP (tos 0xc0, ttl 1, id 0, offset 0, flags [DF], proto IGMP (2), length 40, options (RA))
    10.88.84.102 > 224.0.0.22: igmp v3 report, 1 group record(s) [gaddr 239.255.1.1 to_ex { }]
13:34:16.186495 IP (tos 0xc0, ttl 1, id 0, offset 0, flags [DF], proto IGMP (2), length 40, options (RA))
    10.88.84.102 > 224.0.0.22: igmp v3 report, 1 group record(s) [gaddr 239.255.1.1 to_ex { }]
```
#### mulitcast_snooping off
*igmp traffic on host1 br0 
```
03:57:22.529303 IP (tos 0xc0, ttl 1, id 0, offset 0, flags [DF], proto IGMP (2), length 40, options (RA))
    10.88.84.102 > 224.0.0.22: igmp v3 report, 1 group record(s) [gaddr 239.255.1.1 to_ex { }]
03:57:22.993526 IP (tos 0xc0, ttl 1, id 0, offset 0, flags [DF], proto IGMP (2), length 40, options (RA))
    10.88.84.102 > 224.0.0.22: igmp v3 report, 1 group record(s) [gaddr 239.255.1.1 to_ex { }]
03:57:25.609174 IP (tos 0xc0, ttl 1, id 0, offset 0, flags [DF], proto IGMP (2), length 40, options (RA))
    10.88.84.103 > 224.0.0.22: igmp v3 report, 1 group record(s) [gaddr 239.255.1.1 to_ex { }]
03:57:26.497250 IP (tos 0xc0, ttl 1, id 0, offset 0, flags [DF], proto IGMP (2), length 40, options (RA))
    10.88.84.103 > 224.0.0.22: igmp v3 report, 1 group record(s) [gaddr 239.255.1.1 to_ex { }]

03:57:28.661242 IP (tos 0xc0, ttl 1, id 0, offset 0, flags [DF], proto IGMP (2), length 40, options (RA))
    10.88.84.103 > 224.0.0.22: igmp v3 report, 1 group record(s) [gaddr 239.255.1.1 to_in { }]

03:57:28.661387 IP (tos 0xc0, ttl 1, id 42959, offset 0, flags [none], proto IGMP (2), length 36, options (RA))
    10.88.84.1 > 239.255.1.1: igmp query v3 [max resp time 1.0s]
03:57:28.661443 IP (tos 0xc0, ttl 1, id 42960, offset 0, flags [none], proto IGMP (2), length 36, options (RA))
    10.88.84.1 > 239.255.1.1: igmp query v3 [max resp time 1.0s]

03:57:28.993216 IP (tos 0xc0, ttl 1, id 0, offset 0, flags [DF], proto IGMP (2), length 40, options (RA))
    10.88.84.103 > 224.0.0.22: igmp v3 report, 1 group record(s) [gaddr 239.255.1.1 to_in { }]
03:57:28.993298 IP (tos 0xc0, ttl 1, id 43030, offset 0, flags [none], proto IGMP (2), length 36, options (RA))
    10.88.84.1 > 239.255.1.1: igmp query v3 [max resp time 1.0s]


03:57:29.169749 IP (tos 0xc0, ttl 1, id 0, offset 0, flags [DF], proto IGMP (2), length 48, options (RA))
    10.88.84.102 > 224.0.0.22: igmp v3 report, 2 group record(s) [gaddr 239.255.1.1 is_ex { }] [gaddr 224.0.0.251 is_ex { }]
```
*igmp traffic on host3 eth0
```
13:35:09.866553 IP (tos 0xc0, ttl 1, id 0, offset 0, flags [DF], proto IGMP (2), length 40, options (RA))
    10.88.84.102 > 224.0.0.22: igmp v3 report, 1 group record(s) [gaddr 239.255.1.1 to_ex { }]
13:35:10.362665 IP (tos 0xc0, ttl 1, id 0, offset 0, flags [DF], proto IGMP (2), length 40, options (RA))
    10.88.84.102 > 224.0.0.22: igmp v3 report, 1 group record(s) [gaddr 239.255.1.1 to_ex { }]
13:35:18.350639 IP (tos 0xc0, ttl 1, id 64815, offset 0, flags [none], proto IGMP (2), length 36, options (RA))
    10.88.84.1 > 239.255.1.1: igmp query v3 [max resp time 1.0s]
13:35:18.478725 IP (tos 0xc0, ttl 1, id 64840, offset 0, flags [none], proto IGMP (2), length 36, options (RA))
    10.88.84.1 > 239.255.1.1: igmp query v3 [max resp time 1.0s]
13:35:18.490674 IP (tos 0xc0, ttl 1, id 0, offset 0, flags [DF], proto IGMP (2), length 48, options (RA))
    10.88.84.102 > 224.0.0.22: igmp v3 report, 2 group record(s) [gaddr 239.255.1.1 is_ex { }] [gaddr 224.0.0.251 is_ex { }]
```
### Conclusion by now
from dumped msg above along with info from `mroutectl show igmp` we can found, if any host behind br0 send igmp leave for a specified mcaddress for example:239.255.1.1, mrouted will set group 239.255.1.1's expire time to 3 second and send an igmp query to 239.255.1.1, if any participant want to keep the group, it have to send igmp report in less than 1 second.   

by now i got a conclusion that the reason why group drop happen is that the linux bridge drop any igmp query msg outside 224.0.0.0/24, meanwhile mrouted use user group (such as 239.255.1.1 in test above) to send igmp query when participant leave. host behind linux bridge with multicast snooping on will never get these query msg. 
### Question & Discussion
* the fast leave mechanism in mrouted seems little radical especially in scene multi-participant behind a single interface,any configuration to change this behavior?
* mrouted send igmp query on user group like 239.255.1.1  
  linux bridge drop any igmp query outside 224.0.0.x  
  tried some physical management switch with igmp-snooping ,they all accept/forward igmp query outside 224.0.0.x and do not have this issue  
 which one should we apply fix on mrouted or linux bridge?
* what workaround can we apply right now?

**Comment by troglobit** [comment]
Quite extensive report, but it seems to me you've already figured it out.  Yes, it really is the Linux bridge that is broken here. It shouldn't forward the IGMP Leave message from receiver 2 to the router while it still maintains a forwarding state for receiver 1.  __That is the root cause of your problems__, which you confirmed yourself with an external switch with proper IGMP snooping implemented.

When mrouted (the elected IGMP querier here) receives the Leave message it generates a *Group Specific Query*, like you've seen, with a *Last Member Query Interval*.  As per RFC the max response time is set to one second (the value 10) in those query messages.  This is currently hard coded in mrouted and possibly the only workaround you have.  You could try changing this value from `1` to `10` in the file `src/igmpv2.h`.  This should give your end devices 10 * 3 seconds to respond to the group specific query.

**Comment by realdream** [comment]
actually from my test : 
* external switch did forward `Group Specific Query` when one of the receiver leave group, we can confirm this by tcpdump on router side. The test result is exactly the same as `mulitcast_snooping off` on linux bridge above.  We can also confirm this by watching `mroutectl show igmp`: expire time drop to 2s and then get back to about 258 when one of the receiver leave while the other one not. management switch vender tried:H3C,TPlink
* linux bridge `never` forward  `Group Specific Query`  if multicast snooping is enabled

things I'm thinking:
* physical switch on my hand seems not able to handle forwarding/notforwarding IGMP Leave, so mrouted will always get the leave message , that cause a drop on expire time. I'm also not sure whether switch or route should handle this multi-host interface situation. Is there any standard we can reference? 
* is there any implementation for `multicast_last_member_count` in mrouted, is it possible to handle multi-host interface?

**Comment by realdream** [comment]
found something related https://www.juniper.net/documentation/en_US/junos/topics/topic-map/mcast-igmp-snooping.html
### IGMP Snooping and Proxies
Without a proxy arrangement, IGMP snooping does not generate or introduce queries and reports. It will only “snoop” reports received from all of its interfaces (including multicast-router interfaces) to build its state and group (S,G) database.

Without a proxy, IGMP messages are processed as follows:

Query—All general and group-specific IGMP query messages received on a multicast-router interface are forwarded to all other interfaces (both multicast-router interfaces and host-side interfaces) on the bridge.

Report—IGMP reports received on any interface of the bridge are forwarded toward other multicast-router interfaces. The receiving interface is added as an interface for that group if a multicast routing entry exists for this group. Also, a group timer is set for the group on that interface. If this timer expires (that is, there was no report for this group during the IGMP group timer period), then the interface is removed as an interface for that group.

Leave—IGMP leave messages received on any interface of the bridge are forwarded toward other multicast-router interfaces on the bridge. The Leave Group message reduces the time it takes for the multicast router to stop forwarding multicast traffic when there are no longer any members in the host group.

Proxy snooping reduces the number of IGMP reports sent toward an IGMP router.

### Proxy
Enables the Layer 2 device to actively filter IGMP packets to reduce load on the multicast router. Joins and leaves heading upstream to the multicast router are filtered so that the multicast router has a single entry for the group, regardless of how many active listeners have joined the group. When a listener leaves a group but other listeners remain in the group, the leave message is filtered because the multicast router does not need this information. The status of the group remains the same from the router's point of view.

**Comment by troglobit** [comment]
For a long time there weren't any standard for snooping switches, so there turned up more than one way to do this.  Different vendors finally met, and in the spirit of interop. agreed on the recommendations laid out in [RFC4541](https://tools.ietf.org/html/rfc4541).  The rest of all the required knowledge is spread out across many other RFCs.  One thing that really helps is thinking about when IGMPv1 and IGMPv2 existed, it was a dark time when hubs still roamed the networks, so the standards talk about this: reducing traffic, eg. by report suppression from end devices.  So, a snooping switch needs to take this into consideration, sort of emulating a hubbed network, or completely "hide" its own devices and act as a proxy reporter.  Like I said, different ways to do it ...

The Linux bridge doesn't do it right, as I mentioned, if you forward Leave you must also forward Group Specific queries.  It is the responsibility of the bridge, or switch (popular term), to handle this, not the router.  It's Layer-2 vs Layer-3 basically, the router acts solely on Layer-3.  I'm talking logically here, since there are obviously devices on the market that can act as both switch and router in the same physical box, but they also implement both mechanisms in that box.  (We do at $DAYJOB for instance.)

There is limited code in mrouted for `multicast_last_member_count`, see `igmpv2.h` and the code in `igmp.c` and `igmp_proto.c`.  My first reply details this further.

**Comment by realdream** [comment]
# some update here
In have make a mistake, that I did not config my pysical switch properly, actually mc traffic flood over switch port in previous test, after properly setting, the pysical switch just act like linux bridge, they all not forward group-specific query from mrouted, but forward igmp leave from host side, that make mrouted to drop group.

**Comment by troglobit** [comment]
Still behaves wrong. What's the manufacturer? Some use Linux internally.

**Comment by realdream** [comment]
H3C and tplink, both with igmp snooping but with out igmp proxy

**Comment by troglobit** [comment]
Thanks for the info! I'm mostly curious for when other users ask.

I've been digging around in the code a bit, testing a fix for issue #43, and I did actually find something curious that I'm investigating currently; it seems mrouted doesn't send properly formatted group-specific IGMP querys.   The IP header destination is correct, using the group destination, but the IGMP header has group 0.0.0.0, which is used for general querys.  This could potentially be triggering the behavior you see with the external switches.  If it turns out to be an actual bug I'll add it to the tracker and reference this issue.

**Comment by troglobit** [comment]
So, status update from me. I've fixed the following bugs and implemented a few new features that should help you with your problems:

- [X] Invalid parsing of IGMPv3 membership reports, specifically poor handling of (S,G) join/leave, issue #43
- [X] Allow controlling IGMP Last Member Query Count using `igmp-robustness <2-10>`
- [X] New setting `igmp-query-last-member-interval <1-1024>` to control time between group-specific queries, issue #44 
- [X] Malformed group-specific query, issue #46 

I have no more features or fixes planned for the next release, v4.2. Only minor adjustments to the `mroutectl` tool so it works better with `watch -c mroutectl`.  However, I cannot promise any date for the actual release, so I'd very much appreciate if you could perhaps test the latest GIT master to see if the new setting(s) help so we can close this issue.

Happy New Year! :partying_face:

**Comment by realdream** [comment]
Happy New Year! Thank you very mush for your contribution!
further test some switch these days
seems linux-inside switch suffer from dropping group specific query after enable igmp snooping, even disable `drop unknown` mc traffic
none-linux switch seems works smoothly, with following configuration
```
igmp snooping                   on
drop unknown                    on
igmp report suppression         off
```
also tried latest master, no help for linux-inside switch. 
my project is using industrial management switch, most of it using linux inside :(
### proposal/workarounds for any other who face this issue
* change your switch, do not use linux-based switch
* or add an additional config to disable fastdrop on a specific interface on mrouted side (ignore igmp leave, only prune group after timeout)
* or simply specify igmpv1 on the interace connect to unideal switch

**Comment by troglobit** [comment]
I'm sorry to hear this about the Linux bridge implementation. I know Cumulus guys (now nVidia) have proposed changes to the IGMP snooping implementation.  I'll probably be involved in that in the next coming months, so I hope we can improve the situation, although these improvements will take time to reach end-users such as yourself.

I think the best workaround in your list is to set the `igmpv1` flag on the interface, that completely disables all IGMPv2 LEAVE, IGMPv3 BLOCK(), and IGMPv3 TO_IN() processing (see RFC3376 for details), and all groups learned on that interface will have to time out.  This is effectively the same as your two last listed workarounds.

For faster group membership timeout, the `igmp-query-interval` setting can be turned down from 125 sec to, e.g., 12 sec.

I propose we close this issue, we seem to have exhausted all possible avenues to resolve the problem in any other way.

**Comment by realdream** [comment]
I agree with you

**Comment by troglobit** [comment]
Thank you.  I've spent the better part of the last week fixing the bugs uncovered by this report, and also adding some new features to address shortcomings that have come to light.  Tonight I finalized the v4.2 release, which is available here: https://github.com/troglobit/mrouted/releases/tag/4.2 

(I'll get to the PIM projects eventually, have a few other things to tend to first, sorry.)
